"""AUTO-GENERATED by generate_frozen_reference.py --overwrite (2026-09-21T09:05:22Z).

Frozen, fully expanded cobaya configuration for example2
(source: EXAMPLE_EVALUATE2.yaml resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {
    "As_1e9": 2.128048,
    "H0": 67.27,
    "ROMAN_KL_B1_1": 1.24,
    "ROMAN_KL_B1_10": 2.32,
    "ROMAN_KL_B1_2": 1.36,
    "ROMAN_KL_B1_3": 1.48,
    "ROMAN_KL_B1_4": 1.6,
    "ROMAN_KL_B1_5": 1.72,
    "ROMAN_KL_B1_6": 1.84,
    "ROMAN_KL_B1_7": 1.96,
    "ROMAN_KL_B1_8": 2.08,
    "ROMAN_KL_B1_9": 2.2,
    "ROMAN_KL_DZ_S1": 0.0,
    "ROMAN_KL_DZ_S10": 0.0,
    "ROMAN_KL_DZ_S2": 0.0,
    "ROMAN_KL_DZ_S3": 0.0,
    "ROMAN_KL_DZ_S4": 0.0,
    "ROMAN_KL_DZ_S5": 0.0,
    "ROMAN_KL_DZ_S6": 0.0,
    "ROMAN_KL_DZ_S7": 0.0,
    "ROMAN_KL_DZ_S8": 0.0,
    "ROMAN_KL_DZ_S9": 0.0,
    "ROMAN_KL_M1": 0.0,
    "ROMAN_KL_M10": 0.0,
    "ROMAN_KL_M2": 0.0,
    "ROMAN_KL_M3": 0.0,
    "ROMAN_KL_M4": 0.0,
    "ROMAN_KL_M5": 0.0,
    "ROMAN_KL_M6": 0.0,
    "ROMAN_KL_M7": 0.0,
    "ROMAN_KL_M8": 0.0,
    "ROMAN_KL_M9": 0.0,
    "mnu": 0.06,
    "ns": 0.9645,
    "omegab": 0.0491685,
    "omegam": 0.3156,
    "w": -1.0,
    "w0pwa": -1.0
}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.65
    proposal: 0.4
    latex: 10^9 A_\mathrm{s})
    drop: true
    renames: A
  ns:
    prior:
      min: 0.5
      max: 1.1
    ref:
      dist: norm
      loc: 0.9645
      scale: 0.01
    proposal: 0.01
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 40
      max: 90
    ref:
      dist: norm
      loc: 67.27
      scale: 5
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.005
      max: 0.095
    ref:
      dist: norm
      loc: 0.0491685
      scale: 0.004
    proposal: 0.004
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.095
      max: 0.585
    ref:
      dist: norm
      loc: 0.3156
      scale: 0.015
    proposal: 0.015
    latex: \Omega_\mathrm{m}
    drop: true
  mnu:
    prior:
      min: 0.0
      max: 0.6
    ref:
      dist: norm
      loc: 0.25
      scale: 0.1
    proposal: 0.06
  w0pwa:
    prior:
      min: -5
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}+w_{a,\mathrm{DE}}
    drop: true
  w:
    prior:
      min: -3
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}
  tau:
    value: 0.0697186
    latex: \tau_\mathrm{reio}
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
    derived: true
  wa:
    value: 'lambda w0pwa, w: w0pwa - w'
    latex: w_{a,\mathrm{DE}}
    derived: true
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
    derived: true
    renames:
    - ombh2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
    derived: true
    renames:
    - omch2
  omegal:
    latex: \Omega_\Lambda
    derived: true
    renames:
    - omega_de
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  sigma8:
    latex: \sigma_8
    derived: true
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
    derived: true
  rdrag:
    latex: r_\mathrm{drag}
    derived: true
  yheused:
    latex: Y_P^\mathrm{BBN}
    derived: true
    renames:
    - YHe
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
    derived: true
    renames:
    - omnuh2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  ROMAN_KL_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^1
  ROMAN_KL_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^2
  ROMAN_KL_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^3
  ROMAN_KL_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^4
  ROMAN_KL_DZ_S5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^5
  ROMAN_KL_DZ_S6:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^6
  ROMAN_KL_DZ_S7:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^7
  ROMAN_KL_DZ_S8:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^8
  ROMAN_KL_DZ_S9:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^9
  ROMAN_KL_DZ_S10:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: \Delta z_\mathrm{s,ROMAN_KL}^{10}
  ROMAN_KL_A1_1:
    value: 0.0
    latex: A_\mathrm{1-IA,ROMAN_KL}^1
  ROMAN_KL_A1_2:
    value: 0.0
    latex: A_\mathrm{1-IA,ROMAN_KL}^2
  ROMAN_KL_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,ROMAN_KL}^3
  ROMAN_KL_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,ROMAN_KL}^4
  ROMAN_KL_A1_5:
    value: 0
    latex: A_\mathrm{1-IA,ROMAN_KL}^5
  ROMAN_KL_A1_6:
    value: 0
    latex: A_\mathrm{1-IA,ROMAN_KL}^6
  ROMAN_KL_A1_7:
    value: 0
    latex: A_\mathrm{1-IA,ROMAN_KL}^7
  ROMAN_KL_A1_8:
    value: 0
    latex: A_\mathrm{1-IA,ROMAN_KL}^8
  ROMAN_KL_A2_1:
    value: 0.0
    latex: A_\mathrm{2-IA,Roman}^1
  ROMAN_KL_A2_2:
    value: 0.0
    latex: A_\mathrm{2-IA,Roman}^2
  ROMAN_KL_A2_3:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^3
  ROMAN_KL_A2_4:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^4
  ROMAN_KL_A2_5:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^5
  ROMAN_KL_A2_6:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^6
  ROMAN_KL_A2_7:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^7
  ROMAN_KL_A2_8:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^8
  ROMAN_KL_BTA_1:
    value: 0.0
    latex: A_\mathrm{BTA-IA,Roman}^1
  ROMAN_KL_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^2
  ROMAN_KL_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^3
  ROMAN_KL_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^4
  ROMAN_KL_BTA_5:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^5
  ROMAN_KL_BTA_6:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^6
  ROMAN_KL_BTA_7:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^7
  ROMAN_KL_BTA_8:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^8
  ROMAN_KL_M1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^1
  ROMAN_KL_M2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^2
  ROMAN_KL_M3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^3
  ROMAN_KL_M4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{ROMAN_KL}^4
  ROMAN_KL_M5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^5
  ROMAN_KL_M6:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^6
  ROMAN_KL_M7:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^7
  ROMAN_KL_M8:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^8
  ROMAN_KL_M9:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^9
  ROMAN_KL_M10:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.0004
    ref:
      dist: norm
      loc: 0.0
      scale: 0.0004
    proposal: 0.0004
    latex: m_\mathrm{ROMAN_KL}^{10}
  ROMAN_KL_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{ROMAN_KL}^1
  ROMAN_KL_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{ROMAN_KL}^2
  ROMAN_KL_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{ROMAN_KL}^3
  ROMAN_KL_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{ROMAN_KL}^4
  ROMAN_KL_DZ_L1:
    value: 'lambda ROMAN_KL_DZ_S1: ROMAN_KL_DZ_S1'
    latex: \Delta z_\mathrm{l,Roman}^1
    derived: true
  ROMAN_KL_DZ_L2:
    value: 'lambda ROMAN_KL_DZ_S2: ROMAN_KL_DZ_S2'
    latex: \Delta z_\mathrm{l,Roman}^2
    derived: true
  ROMAN_KL_DZ_L3:
    value: 'lambda ROMAN_KL_DZ_S3: ROMAN_KL_DZ_S3'
    latex: \Delta z_\mathrm{l,Roman}^3
    derived: true
  ROMAN_KL_DZ_L4:
    value: 'lambda ROMAN_KL_DZ_S4: ROMAN_KL_DZ_S4'
    latex: \Delta z_\mathrm{l,Roman}^4
    derived: true
  ROMAN_KL_DZ_L5:
    value: 'lambda ROMAN_KL_DZ_S5: ROMAN_KL_DZ_S5'
    latex: \Delta z_\mathrm{l,Roman}^5
    derived: true
  ROMAN_KL_DZ_L6:
    value: 'lambda ROMAN_KL_DZ_S6: ROMAN_KL_DZ_S6'
    latex: \Delta z_\mathrm{l,Roman}^6
    derived: true
  ROMAN_KL_DZ_L7:
    value: 'lambda ROMAN_KL_DZ_S7: ROMAN_KL_DZ_S7'
    latex: \Delta z_\mathrm{l,Roman}^7
    derived: true
  ROMAN_KL_DZ_L8:
    value: 'lambda ROMAN_KL_DZ_S8: ROMAN_KL_DZ_S8'
    latex: \Delta z_\mathrm{l,Roman}^8
    derived: true
  ROMAN_KL_DZ_L9:
    value: 'lambda ROMAN_KL_DZ_S9: ROMAN_KL_DZ_S9'
    latex: \Delta z_\mathrm{l,Roman}^9
    derived: true
  ROMAN_KL_DZ_L10:
    value: 'lambda ROMAN_KL_DZ_S10: ROMAN_KL_DZ_S10'
    latex: \Delta z_\mathrm{l,Roman}^{10}
    derived: true
  ROMAN_KL_B1_1:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.24
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^1
  ROMAN_KL_B1_2:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.36
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^2
  ROMAN_KL_B1_3:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.47
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^3
  ROMAN_KL_B1_4:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.6
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^4
  ROMAN_KL_B1_5:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.76
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^5
  ROMAN_KL_B1_6:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.47
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^6
  ROMAN_KL_B1_7:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.6
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^7
  ROMAN_KL_B1_8:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.76
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^8
  ROMAN_KL_B1_9:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.76
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^9
  ROMAN_KL_B1_10:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.76
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^{10}
  ROMAN_KL_B2_1:
    value: 0.0
    latex: b_\mathrm{2-Roman}^1
  ROMAN_KL_B2_2:
    value: 0.0
    latex: b_\mathrm{2-Roman}^2
  ROMAN_KL_B2_3:
    value: 0.0
    latex: b_\mathrm{2-Roman}^3
  ROMAN_KL_B2_4:
    value: 0.0
    latex: b_\mathrm{2-Roman}^4
  ROMAN_KL_B2_5:
    value: 0.0
    latex: b_\mathrm{2-Roman}^5
  ROMAN_KL_B2_6:
    value: 0.0
    latex: b_\mathrm{2-Roman}^6
  ROMAN_KL_B2_7:
    value: 0.0
    latex: b_\mathrm{2-Roman}^7
  ROMAN_KL_B2_8:
    value: 0.0
    latex: b_\mathrm{2-Roman}^8
  ROMAN_KL_B2_9:
    value: 0.0
    latex: b_\mathrm{2-Roman}^9
  ROMAN_KL_B2_10:
    value: 0.0
    latex: b_\mathrm{2-Roman}^{10}
  ROMAN_KL_BMAG_1:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^1
  ROMAN_KL_BMAG_2:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^2
  ROMAN_KL_BMAG_3:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^3
  ROMAN_KL_BMAG_4:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^4
  ROMAN_KL_BMAG_5:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^5
  ROMAN_KL_BMAG_6:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^6
  ROMAN_KL_BMAG_7:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^7
  ROMAN_KL_BMAG_8:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^8
  ROMAN_KL_BMAG_9:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^9
  ROMAN_KL_BMAG_10:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^{10}
  ROMAN_KL_PM1:
    value: 0.0
    latex: PM_\mathrm{Roman}^1
  ROMAN_KL_PM2:
    value: 0.0
    latex: PM_\mathrm{Roman}^2
  ROMAN_KL_PM3:
    value: 0.0
    latex: PM_\mathrm{Roman}^3
  ROMAN_KL_PM4:
    value: 0.0
    latex: PM_\mathrm{Roman}^4
  ROMAN_KL_PM5:
    value: 0.0
    latex: PM_\mathrm{Roman}^5
  ROMAN_KL_PM6:
    value: 0.0
    latex: PM_\mathrm{Roman}^6
  ROMAN_KL_PM7:
    value: 0.0
    latex: PM_\mathrm{Roman}^7
  ROMAN_KL_PM8:
    value: 0.0
    latex: PM_\mathrm{Roman}^8
  ROMAN_KL_PM9:
    value: 0.0
    latex: PM_\mathrm{Roman}^9
  ROMAN_KL_PM10:
    value: 0.0
    latex: PM_\mathrm{Roman}^{10}
  ROMAN_KL_B3NL_1:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^1
  ROMAN_KL_B3NL_2:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^2
  ROMAN_KL_B3NL_3:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^3
  ROMAN_KL_B3NL_4:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^4
  ROMAN_KL_B3NL_5:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^5
  ROMAN_KL_B3NL_6:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^6
  ROMAN_KL_B3NL_7:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^7
  ROMAN_KL_B3NL_8:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^8
  ROMAN_KL_B3NL_9:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^9
  ROMAN_KL_B3NL_10:
    value: 0.0
    latex: b_\mathrm{B3NL-Roman}^10
  ROMAN_KL_BK_1:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^1
  ROMAN_KL_BK_2:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^2
  ROMAN_KL_BK_3:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^3
  ROMAN_KL_BK_4:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^4
  ROMAN_KL_BK_5:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^5
  ROMAN_KL_BK_6:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^6
  ROMAN_KL_BK_7:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^7
  ROMAN_KL_BK_8:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^8
  ROMAN_KL_BK_9:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^9
  ROMAN_KL_BK_10:
    value: 0.0
    latex: b_\mathrm{BK-Roman}^10
likelihood:
  roman_kl.combo_3x2pt:
    path: ./projects/roman_kl/tests/frozen/data
    data_file: roman_kl_3x2.dataset
    accuracyboost: 1.0
    integration_accuracy: 1
    kmax_boltzmann: 7.5
    speed: 1
    non_linear_emul: 2
    external_nz_modeling: 0
    use_emulator: 0
    debug: false
    IA_redshift_evolution: 3
    IA_model: 0
    IA_code: 0
    ggl_exclude:
    - - 0
      - 0
    - - 1
      - 0
    - - 1
      - 1
    - - 2
      - 0
    - - 2
      - 1
    - - 2
      - 2
    - - 3
      - 0
    - - 3
      - 1
    - - 3
      - 2
    - - 3
      - 3
    - - 4
      - 0
    - - 4
      - 1
    - - 4
      - 2
    - - 4
      - 3
    - - 4
      - 4
    - - 5
      - 0
    - - 5
      - 1
    - - 5
      - 2
    - - 5
      - 3
    - - 5
      - 4
    - - 5
      - 5
    - - 6
      - 0
    - - 6
      - 1
    - - 6
      - 2
    - - 6
      - 3
    - - 6
      - 4
    - - 6
      - 5
    - - 6
      - 6
    - - 7
      - 0
    - - 7
      - 1
    - - 7
      - 2
    - - 7
      - 3
    - - 7
      - 4
    - - 7
      - 5
    - - 7
      - 6
    - - 7
      - 7
    - - 8
      - 0
    - - 8
      - 1
    - - 8
      - 2
    - - 8
      - 3
    - - 8
      - 4
    - - 8
      - 5
    - - 8
      - 6
    - - 8
      - 7
    - - 8
      - 8
    - - 9
      - 0
    - - 9
      - 1
    - - 9
      - 2
    - - 9
      - 3
    - - 9
      - 4
    - - 9
      - 5
    - - 9
      - 6
    - - 9
      - 7
    - - 9
      - 8
    - - 9
      - 9
    bias_model:
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    add_baryons_on_dv: false
    which_bsims_add_on_dv: antilles-2
    use_baryon_pca: false
    create_baryon_pca: false
    baryon_pca_select_sims: antilles-2-99/antilles-101-378/antilles-380-400
    filename_baryon_pca: ./projects/roman_kl/chains/pca.txt
    external_baryon_suppression: false
    print_datavector: true
    print_datavector_file: ./projects/roman_kl/chains/roman_kl_3x2.modelvector
    type: []
    stop_at_error: false
    version: null
    input_params:
    - H0
    - As
    - ROMAN_KL_DZ_S1
    - ROMAN_KL_DZ_S2
    - ROMAN_KL_DZ_S3
    - ROMAN_KL_DZ_S4
    - ROMAN_KL_DZ_S5
    - ROMAN_KL_DZ_S6
    - ROMAN_KL_DZ_S7
    - ROMAN_KL_DZ_S8
    - ROMAN_KL_DZ_S9
    - ROMAN_KL_DZ_S10
    - ROMAN_KL_A1_1
    - ROMAN_KL_A1_2
    - ROMAN_KL_A1_3
    - ROMAN_KL_A1_4
    - ROMAN_KL_A1_5
    - ROMAN_KL_A1_6
    - ROMAN_KL_A1_7
    - ROMAN_KL_A1_8
    - ROMAN_KL_A2_1
    - ROMAN_KL_A2_2
    - ROMAN_KL_A2_3
    - ROMAN_KL_A2_4
    - ROMAN_KL_A2_5
    - ROMAN_KL_A2_6
    - ROMAN_KL_A2_7
    - ROMAN_KL_A2_8
    - ROMAN_KL_BTA_1
    - ROMAN_KL_BTA_2
    - ROMAN_KL_BTA_3
    - ROMAN_KL_BTA_4
    - ROMAN_KL_BTA_5
    - ROMAN_KL_BTA_6
    - ROMAN_KL_BTA_7
    - ROMAN_KL_BTA_8
    - ROMAN_KL_M1
    - ROMAN_KL_M2
    - ROMAN_KL_M3
    - ROMAN_KL_M4
    - ROMAN_KL_M5
    - ROMAN_KL_M6
    - ROMAN_KL_M7
    - ROMAN_KL_M8
    - ROMAN_KL_M9
    - ROMAN_KL_M10
    - ROMAN_KL_BARYON_Q1
    - ROMAN_KL_BARYON_Q2
    - ROMAN_KL_BARYON_Q3
    - ROMAN_KL_BARYON_Q4
    - ROMAN_KL_DZ_L1
    - ROMAN_KL_DZ_L2
    - ROMAN_KL_DZ_L3
    - ROMAN_KL_DZ_L4
    - ROMAN_KL_DZ_L5
    - ROMAN_KL_DZ_L6
    - ROMAN_KL_DZ_L7
    - ROMAN_KL_DZ_L8
    - ROMAN_KL_DZ_L9
    - ROMAN_KL_DZ_L10
    - ROMAN_KL_B1_1
    - ROMAN_KL_B1_2
    - ROMAN_KL_B1_3
    - ROMAN_KL_B1_4
    - ROMAN_KL_B1_5
    - ROMAN_KL_B1_6
    - ROMAN_KL_B1_7
    - ROMAN_KL_B1_8
    - ROMAN_KL_B1_9
    - ROMAN_KL_B1_10
    - ROMAN_KL_B2_1
    - ROMAN_KL_B2_2
    - ROMAN_KL_B2_3
    - ROMAN_KL_B2_4
    - ROMAN_KL_B2_5
    - ROMAN_KL_B2_6
    - ROMAN_KL_B2_7
    - ROMAN_KL_B2_8
    - ROMAN_KL_B2_9
    - ROMAN_KL_B2_10
    - ROMAN_KL_BMAG_1
    - ROMAN_KL_BMAG_2
    - ROMAN_KL_BMAG_3
    - ROMAN_KL_BMAG_4
    - ROMAN_KL_BMAG_5
    - ROMAN_KL_BMAG_6
    - ROMAN_KL_BMAG_7
    - ROMAN_KL_BMAG_8
    - ROMAN_KL_BMAG_9
    - ROMAN_KL_BMAG_10
    - ROMAN_KL_PM1
    - ROMAN_KL_PM2
    - ROMAN_KL_PM3
    - ROMAN_KL_PM4
    - ROMAN_KL_PM5
    - ROMAN_KL_PM6
    - ROMAN_KL_PM7
    - ROMAN_KL_PM8
    - ROMAN_KL_PM9
    - ROMAN_KL_PM10
    - ROMAN_KL_B3NL_1
    - ROMAN_KL_B3NL_2
    - ROMAN_KL_B3NL_3
    - ROMAN_KL_B3NL_4
    - ROMAN_KL_B3NL_5
    - ROMAN_KL_B3NL_6
    - ROMAN_KL_B3NL_7
    - ROMAN_KL_B3NL_8
    - ROMAN_KL_B3NL_9
    - ROMAN_KL_B3NL_10
    - ROMAN_KL_BK_1
    - ROMAN_KL_BK_2
    - ROMAN_KL_BK_3
    - ROMAN_KL_BK_4
    - ROMAN_KL_BK_5
    - ROMAN_KL_BK_6
    - ROMAN_KL_BK_7
    - ROMAN_KL_BK_8
    - ROMAN_KL_BK_9
    - ROMAN_KL_BK_10
    output_params: []
theory:
  camb:
    version: 1.6.7
    path: ./external_modules/code/CAMB
    speed: 0.3
    stop_at_error: false
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.05
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 50
      kmax: 10
    ignore_obsolete: false
    use_renames: true
    external_primordial_pk: false
    use_non_linear_ratio: false
    renames:
      omegabh2: ombh2
      omegach2: omch2
      omegal: omega_de
      omegak: omk
      yhe: YHe
      yheused: YHe
      YpBBN: Y_p
      omegan2: omnuh2
    input_params:
    - ns
    - As
    - H0
    - mnu
    - w
    - tau
    - wa
    - omegabh2
    - omegach2
    output_params:
    - omegal
    - sigma8
    - age
    - rdrag
    - yheused
    - omegan2
timing: false
"""
