"""Advisory checks E1-E4: the EMUL2 emulated pipelines.

The EXAMPLE_EMUL2 examples replace the Boltzmann code with trained
machine-learning emulators (the emulrdrag, emulbaosn, and emulmps
theory blocks) while the cosmolike likelihood stays exact. An
emulator is an approximation of the exact physics, so these checks
carry NO pass/fail: they measure and report, and every method here
ends green as long as the pipeline runs at all. What is reported:

  - the emulator chi2 against the frozen emulator reference (did the
    installed emulator stack change since the freeze);
  - the emulator chi2 against the exact-physics reference at the same
    cosmology (how accurate the emulator is), followed by the
    recommendation: RECOMMENDED for actual data analysis when
    |emulator - exact| chi2 < 0.2, NOT recommended otherwise;
  - a race check identical in structure to tests 2/4/6/8, printed
    with a warning instead of a failure.

  E1. emul2 example1 (cosmic shear): accuracy and recommendation.
  E2. emul2 example1: race check, advisory.
  E3. emul2 example2 (3x2pt): accuracy and recommendation.
  E4. emul2 example2: race check, advisory.

What makes the accuracy difference meaningful in this project: the
exact NLA references are 0.000000 because each exact configuration
evaluates a synthetic data vector generated by itself at the fiducial
point, while the shipped EMUL2 examples point at the shipped
modelvectors, which sit off the current-code minimum. A difference
taken across those two data choices would mix data mismatch with
emulator error, so load_frozen_info makes each emulated configuration
evaluate the SAME synthetic NLA vector as its exact counterpart
(including the counterpart's data-vector layout; see
cocoa_test_utils.load_frozen_info). |emulator - exact| is then the
emulator error at the same data and the same cosmology, and nothing
else.

Three more caveats a reader should know before trusting the deltas.
First, the emulated configurations sample fewer parameters than the
exact ones (mnu is fixed inside the emulator training; its fixed
value 0.06 equals the exact fiducial, so the accuracy comparison
stays at one physical point, but the race rows drop the mnu
perturbation). Second, the trained-network files are read from
external_modules/data/emultrf (pinned by the EMULTRF keys in
set_installation_options.sh), NOT from the frozen state: retraining
or updating the emulators changes these numbers, and detecting that
is part of this file's job. Third, the network device is frozen to
"cpu" so the numbers do not depend on GPU availability.

To run (from the Cocoa/ folder, cocoa environment active,
start_cocoa.sh sourced):

    python -m pytest ./projects/roman_kl/tests/test_emul2.py
"""

import os

# OpenMP reads OMP_NUM_THREADS when the compiled libraries load, so
# this must run before ANY cobaya/cosmolike import in the process.
os.environ["OMP_NUM_THREADS"] = "4"

import sys
import unittest

# The tests folder is not a package; put it on the import path so the
# shared harness resolves no matter where pytest was launched from.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cocoa_test_utils as u

# The recommendation threshold on |emulator - exact| chi2. It equals
# CHI2_TOLERANCE on purpose: the reference tests allow the exact
# pipeline a 0.2 chi2 band, and an emulator whose own error already
# rivals that band would eat the whole error margin of a real
# analysis.
RECOMMENDATION_LIMIT = u.CHI2_TOLERANCE


class TestEmul2Advisory(unittest.TestCase):
    """Advisory checks E1-E4, sharing one frozen-state verification.

    setUpClass runs once: it moves to ROOTDIR, verifies every frozen
    file against the SHA-256 manifest, and loads the frozen reference
    chi2 values. The manifest check still applies here: the frozen
    emulator CONFIGURATIONS are pinned even though the trained-network
    files are not.
    """

    @classmethod
    def setUpClass(cls):
        u.require_cocoa_environment()
        u.verify_frozen()
        cls.reference = u.load_reference()

    def _accuracy_check(self, name, example, label):
        """Evaluate one emulated configuration and print the verdict.

        Arguments:
          name    = the advisory label (E1 or E3) for the report.
          example = a key of cocoa_test_utils.EXAMPLES with the
                    "emulator" flag.
          label   = one line naming the emulated configuration.
        """
        chi2 = u.single_model_chi2(example, tatt=False)
        frozen_ref = self.reference[f"{example}_nla"]
        exact_ref = self.reference[u.EXAMPLES[example]["exact_reference"]]
        u.report_emul2_advisory(f"{name}: {label}", chi2, frozen_ref,
                                exact_ref, RECOMMENDATION_LIMIT)

    def _race_check(self, name, example, label):
        """Run one advisory race check on an emulated configuration.

        Arguments:
          name    = the advisory label (E2 or E4) for the report.
          example = a key of cocoa_test_utils.EXAMPLES with the
                    "emulator" flag.
          label   = one line naming the emulated configuration.
        """
        u.assert_omp_threads()
        fresh, tenth = u.ten_in_a_row_chi2(example, tatt=False)
        u.report_emul2_race(f"{name}: {label}", fresh, tenth)

    def test_e1_emul2_example1_accuracy(self):
        """emul2 example1: accuracy against the exact chi2, advisory."""
        self._accuracy_check("E1", "emul2_example1",
                             "example1 (cosmic shear, emulated)")

    def test_e2_emul2_example1_race(self):
        """emul2 example1: 10-in-a-row race check, advisory."""
        self._race_check("E2", "emul2_example1",
                         "example1 (cosmic shear, emulated) race check")

    def test_e3_emul2_example2_accuracy(self):
        """emul2 example2: accuracy against the exact chi2, advisory."""
        self._accuracy_check("E3", "emul2_example2",
                             "example2 (3x2pt, emulated)")

    def test_e4_emul2_example2_race(self):
        """emul2 example2: 10-in-a-row race check, advisory."""
        self._race_check("E4", "emul2_example2",
                         "example2 (3x2pt, emulated) race check")


if __name__ == "__main__":
    unittest.main(verbosity=2)
