"""Unit tests 1-4: the cosmic-shear likelihood on the frozen test data.

Cosmic shear is the correlation of galaxy shape distortions produced by
weak gravitational lensing; in this Fourier-space project its data
vector holds the shear angular power spectra C_l^ss of every source-bin
pair in 20 multipole bands (l = 20 to 4000). The tests evaluate the
roman_kl.cosmic_shear likelihood on the frozen copy of example1's
configuration: a complete configuration and data set stored under
tests/frozen/ and pinned by a SHA-256 manifest, so edits to the live
example files cannot change what the tests evaluate (the docstring of
cocoa_test_utils.py says more). The NLA tests evaluate a synthetic data
vector generated by the same model at the fiducial point, so the frozen
reference chi2 is zero up to rounding. The four tests:

  1. chi2 at the frozen fiducial point, within CHI2_TOLERANCE (0.2) of
     the frozen reference value.
  2. race check: on one model, the fiducial evaluated fresh and again
     as the 10th of 10 cosmologies in a row must agree to
     RACE_TOLERANCE (1e-4). A disagreement means state leaked between
     evaluations or OpenMP threads raced.
  3. the same comparison as test 1 with the TATT intrinsic-alignment
     model (IA_model: 1) and ROMAN_KL_A2_1 = 0.05, ROMAN_KL_BTA_1 = 0.05,
     ROMAN_KL_A2_2 = -1.51541 replacing the NLA point's zeros, against a
     TATT-generated data vector. A1 is fixed to 0 in this configuration,
     so the NLA tests carry no intrinsic alignment and under TATT only
     the tidal-torquing A2 terms contribute (the B_TA terms multiply A1).
  4. the same race check as test 2 with the TATT model.

To run (from the Cocoa/ folder, cocoa environment active,
start_cocoa.sh sourced):

    python -m pytest ./projects/roman_kl/tests/data_vector
"""

import os

# OpenMP reads OMP_NUM_THREADS when the compiled libraries load, so
# this must run before any cobaya/cosmolike import in the process.
# "4" is cocoa_test_utils.REQUIRED_OMP_THREADS: the race checks need
# several threads, and the frozen references were computed with four.
os.environ["OMP_NUM_THREADS"] = "4"

import sys
import unittest

# The shim cocoa_test_utils.py (this project's data bound to the shared
# test machinery) lives one folder up, in tests/; insert(0, ...) puts
# that folder first on the module search path, so a direct run of this
# file and the worker subprocesses import this project's shim.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import cocoa_test_utils as u

EXAMPLE = "example1"


class TestExample1CosmicShear(unittest.TestCase):
    """Tests 1-4, sharing one frozen-state verification.

    setUpClass runs once before the tests: it moves to ROOTDIR,
    verifies every frozen file against the SHA-256 manifest (an edited
    frozen state must fail loudly before any physics runs), and loads
    the frozen reference chi2 values.
    """

    @classmethod
    def setUpClass(cls):
        """Check the Cocoa shell, verify the frozen files, load the references.

        unittest calls this once, before the first test of the class;
        @classmethod passes the class itself as cls, so cls.reference
        (the frozen reference chi2 values) is shared by every test.
        """
        u.require_cocoa_environment()
        u.verify_frozen()
        cls.reference = u.load_reference()

    def test_1_chi2_matches_frozen_reference(self):
        """chi2 at the frozen NLA point stays within 0.2 of the reference."""
        chi2 = u.single_model_chi2(EXAMPLE, tatt=False)
        ref = self.reference[f"{EXAMPLE}_nla"]
        u.report_chi2_test(
            1, "example1 (cosmic shear, NLA) chi2 vs frozen reference",
            chi2, ref, u.CHI2_TOLERANCE)
        # :.6f in the failure message = fixed six decimals
        self.assertLess(
            abs(chi2 - ref), u.CHI2_TOLERANCE,
            msg=f"chi2 = {chi2:.6f} vs frozen reference {ref:.6f} "
                f"(|delta| >= {u.CHI2_TOLERANCE})")

    def test_2_no_race_condition_ten_in_a_row(self):
        """The fiducial as 10th of 10 cosmologies matches a fresh run."""
        u.assert_omp_threads()
        # the call returns a (fresh, tenth) pair; the assignment
        # unpacks it into the two names
        fresh, tenth = u.ten_in_a_row_chi2(EXAMPLE, tatt=False)
        u.report_race_test(
            2, "example1 (cosmic shear, NLA) race check: 10 cosmologies in a row",
            fresh, tenth, u.RACE_TOLERANCE)
        self.assertLess(
            abs(tenth - fresh), u.RACE_TOLERANCE,
            msg=f"10th-in-a-row chi2 = {tenth:.8f} vs fresh {fresh:.8f}")

    def test_3_chi2_matches_frozen_reference_tatt(self):
        """Test 1 repeated with the TATT IA model and nonzero A2/BTA."""
        chi2 = u.single_model_chi2(EXAMPLE, tatt=True)
        ref = self.reference[f"{EXAMPLE}_tatt"]
        u.report_chi2_test(
            3, "example1 (cosmic shear, TATT) chi2 vs frozen reference",
            chi2, ref, u.CHI2_TOLERANCE)
        self.assertLess(
            abs(chi2 - ref), u.CHI2_TOLERANCE,
            msg=f"TATT chi2 = {chi2:.6f} vs frozen reference {ref:.6f} "
                f"(|delta| >= {u.CHI2_TOLERANCE})")

    def test_4_no_race_condition_ten_in_a_row_tatt(self):
        """Test 2 repeated with the TATT IA model."""
        u.assert_omp_threads()
        fresh, tenth = u.ten_in_a_row_chi2(EXAMPLE, tatt=True)
        u.report_race_test(
            4, "example1 (cosmic shear, TATT) race check: 10 cosmologies in a row",
            fresh, tenth, u.RACE_TOLERANCE)
        self.assertLess(
            abs(tenth - fresh), u.RACE_TOLERANCE,
            msg=f"TATT 10th-in-a-row chi2 = {tenth:.8f} vs fresh {fresh:.8f}")


# __name__ is "__main__" only when this file runs directly as a
# script; pytest imports the module instead, so this block stays
# idle under pytest. unittest.main runs every test method of the
# classes above and prints one line per method (verbosity=2).
if __name__ == "__main__":
    unittest.main(verbosity=2)
